create tablespace UNA datafile '/opt/oracle/oradata/XEPDB1/UNA.dbf' size 100M

alter session set "_ORACLE_SCRIPT" = true;

create user KARAUZ identified by "una" default tablespace UNA;

grant dba to KARAUZ;

GRANT CONNECT, RESOURCE TO KARAUZ;

DROP USER KARAUZ;

ALTER USER KARAUZ QUOTA UNLIMITED ON UNA;

GRANT SELECT ON V_$SESSION TO KARAUZ;
GRANT SELECT ON V_$STATNAME TO KARAUZ;
GRANT SELECT ON V_$MYSTAT TO KARAUZ;
GRANT SELECT_CATALOG_ROLE TO KARAUZ;

GRANT DEBUG CONNECT SESSION TO KARAUZ;
GRANT DEBUG ANY PROCEDURE TO KARAUZ;
GRANT CREATE MATERIALIZED VIEW TO KARAUZ;
GRANT QUERY REWRITE TO KARAUZ;
GRANT GLOBAL QUERY REWRITE TO KARAUZ;